# This is a basic workflow to help you get started with Actions

name: Tutorial_Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # container: lgatica/openssh-client

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        uses: contention/rsync-deployments@v1.0.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          args: "-avzr --delete www@zzsqwq.cn:/home/www/tutorial/"
          
          # cp  ${{ secrets.DEPLOY_KEY }} .
          # chmod 600 ./DEPLOY_KEY
          # ssh -o stricthostkeychecking=no -i ./DEPLOY_KEY www@zzsqwq.cn "rm -rf /home/docs/tutorial && mkdir /home/docs/tutorial"
          # scp -o stricthostkeychecking=no -r -i ./DEPLOY_KEY . root@zzsqwq.cn:/home/docs/tutorial/
